
version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    networks:
      - prestashopsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 127.0.0.1:8083:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 30M
    networks:
      - prestashopsite
  # prestashop
  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop
    ports:
      - 127.0.0.1:8002:80
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      PRESTASHOP_DB_HOST: db:3306
      PRESTASHOP_DB_USER: prestashop
      PRESTASHOP_DB_PASSWORD: prestashop
    networks:
      - prestashopsite
networks:
  prestashopsite:
volumes:
  db_data:


